name: Windows 2022 RDP Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download Required Files
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://storage.curvee.eu.org/start-2019.bat -OutFile start.bat
        Invoke-WebRequest https://storage.curvee.eu.org/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://storage.curvee.eu.org/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://storage.curvee.eu.org/loop.bat -OutFile loop.bat

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Copy-Item wallpaper.png -Destination "C:\Users\Public\Desktop\wallpaper.png"
        Copy-Item wallpaper.bat -Destination "C:\Users\Public\Desktop\wallpaper.bat"

    - name: Start Ngrok and Loop Script
      run: |
        .\ngrok\ngrok.exe tcp --region ap 3389 &
        cmd /c loop.bat
